config/routes.rb
AbacoAdmins::Application.routes.draw do
namespace :admin do
  resources :countries do
    member do
      get 'short'
      post 'toggle'
      post 'enable'
    end

    collection do
      post 'disable_all'
    end
  end
end

  

end

app/models/abaco_admin.rb
class AbacoAdmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable, 
    :validatable, :token_authenticatable, :lockable, :timeoutable
  attr_accessible :email, :password

  has_many :admin_access_grants, :dependent => :delete_all

  def to_s
    self.email
  end


  self.token_authentication_key = "oauth_token"

  def apply_omniauth(omniauth)
    authentications.build(:provider => omniauth['provider'], 
      :uid => omniauth['uid'])
  end

  def self.find_for_token_authentication(conditions)
    where(["#{AdminAccessGrant.table_name}.access_token = ? AND (#{
      AdminAccessGrant.table_name}.access_token_expires_at IS NULL OR #{
      AdminAccessGrant.table_name}.access_token_expires_at > ?)", 
      conditions[token_authentication_key], Time.now]).
      joins(:admin_access_grants).select("#{self.table_name}.*").first
  end
end

app/models/admin_access_grant.rb
class AdminAccessGrant < ActiveRecord::Base
  belongs_to :abaco_admin
  belongs_to :app_client
  before_create :generate_tokens


  def self.prune!
    delete_all(["created_at < ?", 2.hours.ago])
  end

  def self.authenticate(code, application_id)
    AdminAccessGrant.where("code = ? AND app_client_id = ?", code, application_id).first
  end

  def generate_tokens
    self.code, self.access_token, self.refresh_token = SecureRandom.hex(16), SecureRandom.hex(16), SecureRandom.hex(16)
  end

  def redirect_uri_for(redirect_uri)
    if redirect_uri =~ /\?/
      redirect_uri + "&code=#{code}&response_type=code&state=#{state}"
    else
      redirect_uri + "?code=#{code}&response_type=code&state=#{state}"
    end
  end

  # Note: This is currently configured through devise, and matches the AuthController access token life
  def start_expiry_period!
    self.update_attribute(:access_token_expires_at, Time.now + Devise.timeout_in)
  end
end

app/models/app_client.rb
class AppClient < ActiveRecord::Base
  def self.authenticate(app_id, app_secret)
    where(["app_id = ? AND app_secret = ?", app_id, app_secret]).first
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true,length: {minimum: 1, maximum: 50}
	validates :language, presence: true, length: {minimum: 1, maximum: 15}
	validates :population, allow_nil: true, numericality: { only_integer: true, greater_than: 500}
	before_validation :strip_whitespace, :only => [:name, :language, :population]
	attr_accessible :language, :name, :population, :disabled
	def to_s
		self.name
	end

	def strip_whitespace
		self.name = self.name.strip
		self.language = self.language.strip
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :locked_at


  def to_s
    self.email
  end

end 

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    layout 'application'
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
	resource_controller
 	#add_breadcrumb get_controller_name, :collection_path
 	add_default_resource_methods

 	def disable_all
 		Country.update_all(disabled: true)
 		flash[:notice]=I18n.t(:countries_disabled)
 		redirect_to(collection_url)
 	end

 	def enable
 		load_object
 		@object.disabled=false
 		begin
	 		@object.save!
	 		flash[:notice]=I18n.t(:country_enabled)
 		rescue
 			logger.exc
 			flash[:notice]=I18n.t(:country_enabled_fail)
 		end
 		redirect_to(collection_url)
 	end
end

app/controllers/application_controller.rb
require 'ajax_default_resource'
require 'will_paginate_render'
class ApplicationController < ActionController::Base
  helper_method :get_user, :is_xhr?
  add_breadcrumb :home, "/"


  around_filter :manage_context

  def manage_context
    logger.debug(params.to_yaml)
    logger.info(request.session_options[:id])
    #Thread.current[:user] = session[:usuario_id]
    
    begin
      yield
    rescue 
      logger.exc($!, :error, -1)
      render :file => 'public/500.html', :status => 500, :layout => false
    ensure  
      #Thread.current[:user] = nil
      logger.info(flash[:notice]) if flash[:notice]  
    end
  end
  

  protect_from_forgery
  protected
  #Gets the controllers name translation 
  def self.get_controller_name
    I18n.t(self.name.underscore.split('/').last.sub!('_controller', ''))
  end
  #Lets know if the current request is ajax
  def is_xhr?
    request.xhr?
  end

  def get_user
    
  end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def list_id
		"list_#{suffix}"
	end

	def footer_id
		"footer_#{suffix}"
	end

	def cancel_button_tag(url = "", &block)
		button_tag t(:cancel), :type => "button", :class => (is_xhr? ? "remote_cancel_button btn" : "cancel_button btn"), :data => {:url => url}, &block
	end

  def edit_abaco_admin_registration_path(*args)
    ''
  end

  def icon(icon, before_text="", after_text="", options={})
    "<span>#{before_text}</span><i class='fa #{icon}'></i><span>#{after_text}</span>"
  end
end

app/views/admin/countries/_edit.html.erb
  <%= simple_form_for(@object, :url => object_url(@object), :remote => is_xhr?, :method => :put) do |f| %>
	    <%= render :partial => "form", :locals => { :f => f } %>
        <div class="form-horizontal control-label">
        </div>
		<%= f.button :submit %>
    	<%= cancel_button_tag(collection_url)%>
  <% end %>

app/views/admin/countries/_form.html.erb
<%= f.input :name %>
<%= f.input :language %>
<%= f.input :population %>

app/views/admin/countries/_index.html.erb
<% content_for :search_content do %>
<div class="row-fluid">
    <%= form_for @search, :url => collection_url, :method => :get do |f| %>
        <%= f.text_field :name_cont, :class=>"input-medium search-query" -%>
        <%= button_tag :class=> "btn btn-purple btn-small" do %>
            <%=t(:search)%>
            <i class='icon-search icon-on-right bigger-110'></i>
        <%end%>
    <% end %>
</div>
<%end %>
<% content_for :options_content do %>
    <li>
        <%= link_to t('new_registry'), new_object_url %> 
        <%= link_to t('disable_all'), disable_all_admin_countries_url, :method => :post %> 
    </li>
<% end %> 
<div id="table_report_wrapper" class="dataTables_wrapper" role="grid">
    <table class="table table-striped table-bordered table-hover dataTable">
            <thead>
            <tr>
                <th class="id_column"> <%= t(:Id) %> </th>
                <th> <%= t('name') %> </th>
                <th> <%= t('disabled') %> </th>
                <th class="span1 td-actions"></th>
            </tr>
        </thead>
        <tbody id="<%= list_id-%>">
            <%= render :partial => "row", :collection=> @collection %>
        </tbody>
    </table>
    <%= render 'shared/pagination_counter' %>
</div>

app/views/admin/countries/_new.html.erb
  <%= simple_form_for(@object, :url => collection_url, :remote => is_xhr?) do |f| %>
	    <%= render :partial => "form", :locals => { :f => f } %>
		<%= f.button :submit %>
		<%= cancel_button_tag(collection_url)%>
  <% end %>

app/views/admin/countries/_row.html.erb
<% item = row if row %>
<tr id="<%= dom_id(item)%>" style='<%= defined?(hide) ? "display:none" : '' -%>'  >
	
	<td class="id_column"><%= item.id %></td>
	<td><%= item.to_s-%></td>
	<td><%= item.disabled%></td>
	<td class="span1 td-actions">
		<%#= link_to( t(:delete), object_url(item), :method => :delete, :confirm => t(:delete_register), :class => 'btn btn-info')-%>
		<div class="visible-desktop btn-group">
			<%= link_to( edit_object_url(item), :class => 'btn btn-mini btn-warning') do -%>
				<i title='<%= t(:edit)%>' class='icon-edit bigger-120'></i>
			<%end%>
			<%= link_to( object_url(item), :method => :delete, :confirm => t(:delete_register), :class => 'btn btn-mini btn-danger') do -%>
				<i title='<%= t(:delete)%>' class="icon-trash bigger-120"></i>
			<%end%>
			<%= link_to( enable_admin_country_url(item), :method => :post,:class => 'btn btn-mini btn-danger') do -%>
				<i title='<%= t(:enable)%>' class="icon-trash bigger-120"></i>
			<%end%>
		</div>
	</td>
</tr>

app/views/admin/countries/_show.html.erb
<%= simple_form_for(@object, :defaults=> {:as => :text_output}, :url => collection_url, :remote => is_xhr?, :method => :get) do |f| %>
    <%= f.input :name %>
    <%= f.input :language %>
	<%= f.input :population %>
<%end%>

app/views/admin/countries/edit.html.erb
<%= render :partial => "edit" %>

app/views/admin/countries/index.html.erb
 <%= render :partial => "index" %>

app/views/admin/countries/new.html.erb
<%= render :partial => "new" %>

app/views/admin/countries/show.html.erb
<%= render :partial => "show" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Saberes+ Viewer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!--[if IE 7]>
    <%= stylesheet_link_tag "font-awesome-ie7" %>
    <![endif]-->

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:400,300" %>

    <!--[if lte IE 8]>
    <%= stylesheet_link_tag "ace-ie.min" %>
    <![endif]-->

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class='navbar-fixed'>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a href="/" class="brand"> <%= image_tag 'logo_saberes_plus_28.png'%> <small> Saberes+ </small> </a><!--/.brand-->

          <ul class="nav ace-nav pull-right">

            <li class="light-blue user-profile">
              <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle"> <%= image_tag('avatar2.png', :class=>'nav-user-photo',  :alt=>'')%> <span id="user_info"> <small>Welcome,</small> <%= get_user.to_s%></span> <i class="icon-caret-down"></i> </a>

              <ul class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer" id="user_menu">
                
              </ul><!--/#user_menu-->
            </li>
          </ul><!--/.ace-nav-->
        </div><!--/.container-fluid-->
      </div><!--/.navbar-inner-->
    </div>

    <div class="container-fluid" id="main-container">
      <a id="menu-toggler" href="#"> <span></span> </a>

      <div id="sidebar" class='fixed'>
        <ul class="nav nav-list">
         
          <li class='open active'>
                            
          </li>
          <li class='open'>
            <%= link_to("#") do %>
              <i class="icon-tasks"></i> <span><%= t(:options)%></span>
            <% end%>  
            
            <ul class="submenu">
              <%= yield :options_content%>
            </ul><!--/.submenu-->
          </li><!--/.open .active -->
        </ul><!--/.nav-list-->

        <div id="sidebar-collapse">
          <i class="icon-double-angle-left"></i>
        </div>
      </div>

      <div id="main-content" class="clearfix">
        <div id="breadcrumbs">
          <%= render :partial => "shared/breadcrumbs" %>
        </div>
        
        <div id="page-content" class="clearfix">
          <div class="row-fluid">
            <%= yield :search_content %>
                  <%= bootstrap_flash %>
            <%= yield %>
          </div><!--/row-->
          </div><!--/#page-content-->
      </div><!--/#main-content-->
    </div><!--/.fluid-container#main-container-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_barra.html.erb
<%
if session[:profile_menu]
  position = 80
  MENU_YAML[session[:profile_menu]]['menus'].keys.sort.each_with_index do |menu_key, i| %>
    <div class="item_menu" style="left:<%= position -%>px;">
      <%= link_to t(MENU_YAML[session[:profile_menu]]['menus'][menu_key]['name'].to_sym), MENU_YAML[session[:profile_menu]]['menus'][menu_key]['url'] -%>
      <% position += (t(MENU_YAML[session[:profile_menu]]['menus'][menu_key]['name']).length * 7) + 20 %>
      <div  class="sub_menu" >
        <% unless MENU_YAML[session[:profile_menu]]['menus'][menu_key]['menus'].blank? -%>
          <%for submenu_key in MENU_YAML[session[:profile_menu]]['menus'][menu_key]['menus'].keys.sort %>
            <div  class="item_sub_menu" ><%= link_to t(MENU_YAML[session[:profile_menu]]['menus'][menu_key]['menus'][submenu_key]['name'].to_sym),
                                                     MENU_YAML[session[:profile_menu]]['menus'][menu_key]['menus'][submenu_key]['url'] -%></div>
          <%end -%>
        <% end -%>
      </div>
    </div>
    <% end -%>
  <% end -%>
<div id="clip"  style="left:-999em;">&nbsp;</div>

app/views/shared/_breadcrumbs.html.erb
<%=render_breadcrumbs()%>

app/views/shared/_content_manager_navigation.html.erb
<li class='open <%='active' if params[:controller].to_s.match(/^content_manager\//)  %>'>
	<a href="#" class="dropdown-toggle"> <i class="icon-cogs"></i> <span><%= t(:content_manager)%></span> <b class="arrow icon-angle-down"></b> </a>

	<ul class="submenu">
		<li>
			<%= link_to(content_manager_contents_path) do %>
				 <i class="icon-double-angle-right"></i> <%= t(:contents)%> </a>
			<% end%>
		</li>
		<li>
			<%= link_to(content_manager_countries_path) do %>
				 <i class="icon-double-angle-right"></i> <%= t(:countries)%> </a>
			<% end%>
		</li>
	</ul>
</li>

app/views/shared/_notifications.js.erb
<% if flash[:notice] -%>
  
  show_notification(("<%=escape_javascript(render(:partial => "shared/warning", :locals => {:flash => flash})) -%>"));
<% end -%>

app/views/shared/_pagination_counter.html.erb
<% unless  @collection.blank? %>
    
    <div class="row-fluid">
        <div class="span6">
            <div class="dataTables_info" id="table_report_info">
                <%= page_entries_info @collection %>
            </div>
        </div>
        <div class="span6">

            <div class="dataTables_paginate paging_bootstrap pagination">
                <%= will_paginate @collection %>
                <%#will_paginate @collection#, :renderer=>WillPaginateRender %>
                <!--   
                <ul>

                    <li class="prev disabled">
                        <a href="#">
                        <i class="icon-double-angle-left"></i>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li class="next">
                        <a href="#">
                        <i class="icon-double-angle-right"></i>
                        </a>
                    </li>
                </ul>-->
                
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_user_navigation.html.erb
<li class='open <%='active' if params[:controller].to_s.match(/^content_manager\//)  %>'>
	<a href="#" class="dropdown-toggle"> <i class="icon-book"></i> <span><%= t(:user)%></span> <b class="arrow icon-angle-down"></b> </a>
<!--
	<ul class="submenu">
		<li>
			<a href="elements.html"> <i class="icon-double-angle-right"></i> Elements </a>
		</li>

		<li>
			<a href="buttons.html"> <i class="icon-double-angle-right"></i> Buttons &amp; Icons </a>
		</li>
	</ul>
-->
</li>

app/views/shared/_warning.html.erb
<% if flash[:notice] -%>
   <p><%= flash[:notice] %></p>
  <%flash.discard()%>
<% end -%>

app/views/shared/crud/create.js.erb
<%= render 'shared/notifications'-%>
$.fancybox.close();
$("#<%=list_id-%>").prepend("<%=escape_javascript(render(:partial => "row", :locals => {:row => @object, :hide => true})) -%>");
$('#<%= dom_id(@object)-%>').fadeIn();
$('#<%= footer_id %> #counter_number').html(parseInt($('#<%= footer_id %> #counter_number').html())+1);
$('a[rel=lightbox]').fancybox(fancybox_options);

app/views/shared/crud/create_fail.js.erb
<%= render 'shared/notifications'-%>

//jQuery("#warning").html("<%=escape_javascript(render(:partial => "shared/warning", :locals => {:flash => flash})) -%>");
$.fancybox("<%=escape_javascript(render(:partial => "new")) -%>");

app/views/shared/crud/destroy.js.erb
<%= render 'shared/notifications'-%>
$('#<%= dom_id(@object)-%>').fadeOut(1000);
$('#<%= footer_id %> #counter_number').html(parseInt($('#<%= footer_id %> #counter_number').html())-1);
$('#<%= dom_id(@object)-%>').remove();

app/views/shared/crud/destroy_fail.js.erb
<%= render 'shared/notifications'-%>

app/views/shared/crud/update.js.erb
<%= render 'shared/notifications'-%>
$.fancybox.close();
$('#<%= dom_id(@object)-%>').replaceWith("<%=escape_javascript(render(:partial => "row", :locals => {:row => @object})) -%>", 
function(){
	$("#fader").animate({marginTop: "500px"});
});
$('a[rel=lightbox]').fancybox(fancybox_options);

app/views/shared/crud/update_fail.js.erb
<%= render 'shared/notifications'-%>
$.fancybox("<%=escape_javascript(render(:partial => "edit")) -%>");

app/views/template/crud/_edit.html.erb
  <%= simple_form_for(@object, :url => object_url(@object), :remote => is_xhr?, :method => :put) do |f| %>
	<fieldset>
		<legend><%= t(:edit_record, :record_name => t(object_name.downcase))%></legend>
	    <%= render :partial => "form", :locals => { :f => f } %>
	</fieldset>
		<%= f.button :submit %>
    	<%= cancel_button_tag(collection_url)%>
  <% end %>

app/views/template/crud/_index.html.erb
<h3><%= link_to t(:start), {:controller => "/start"},{} -%>&rarr; </h3>

<% content_for :sidebar do %>
<div class="info">
    <h2><%= t(:options) -%></h2>
    <%= search_form_for @search, :url => collection_url, :builder => SimpleForm::FormBuilder, :defaults => {:required => false} do |f| %>
        <%= f.input :student_full_name_cont -%>
        <%= f.input :grade_id_eq, :collection => Grade.all -%>
        <%= f.submit t(:search) %>
        
    <% end %>
</div>
<%end %>
<table class="azul">
    <thead>
        <tr>
            <th></th>
            <th> <%= t(:Id) %> </th>
            <th colspan="2"> <%= t('evaluacion') %> </th>
        </tr>
    </thead>
    <tbody id="<%= list_id-%>">
        <%= render :partial => "row", :collection=> @collection %>
    </tbody>
     <tfoot id="<%= footer_id%>">
        <tr>
            <th colspan="3">
                <%= render :partial => 'shared/pagination_counter', :locals => {:collection=> @collection} -%>
            </th>
        </tr>
    </tfoot>
</table>

app/views/template/crud/_new.html.erb
  <%= simple_form_for(@object, :url => collection_url, :remote => is_xhr?) do |f| %>
	<fieldset>
	<legend><%= t(:create_record, :record_name => t(object_name.downcase))%></legend>
	    <%= render :partial => "form", :locals => { :f => f } %>
	</fieldset>
		<%= f.button :submit %>
		<%= cancel_button_tag(collection_url)%>
  <% end %>

app/views/template/crud/_row.html.erb
<% item = row if row %>
<tr id="<%= dom_id(item)%>" style='<%= defined?(hide) ? "display:none" : '' -%>'  >
	<td> 
	<%= link_to( image_tag("edit.gif",
	:border=>0, :alt => t(:edit), :title=>t(:edit)), edit_object_url(item), :rel=>:lightbox)-%>
	<%= link_to( image_tag("anular.gif",
	:border=>0, :alt => t(:delete), :title=>t(:delete)), object_url(item), :method => :delete, :confirm => t(:delete_register))-%>
	
	
	</td>
	<td><%= item.id %></td>
	<td><%= item.name-%></td>
</tr>

app/views/template/crud/_show.html.erb
<fieldset>
  <legend><%= t(:show)%> </legend>
  
</fieldset>

app/views/template/crud/edit.html.erb
<%= render :partial => "edit" %>

app/views/template/crud/index.html.erb
 <%= render :partial => "index" %>

app/views/template/crud/new.html.erb
<%= render :partial => "new" %>

app/views/template/crud/show.html.erb
<%= render :partial => "show" %>